
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getLogPath() : Promise<string> {
    return await TAURI_INVOKE("get_log_path");
},
async exportDiagnostics() : Promise<boolean> {
    return await TAURI_INVOKE("export_diagnostics");
},
async getDataDir() : Promise<string | null> {
    return await TAURI_INVOKE("get_data_dir");
},
async openLogDir() : Promise<null> {
    return await TAURI_INVOKE("open_log_dir");
},
async openDataDir() : Promise<null> {
    return await TAURI_INVOKE("open_data_dir");
},
async resetApplication() : Promise<null> {
    return await TAURI_INVOKE("reset_application");
},
async setLogLevel(level: string) : Promise<null> {
    return await TAURI_INVOKE("set_log_level", { level });
},
async getVersion() : Promise<string> {
    return await TAURI_INVOKE("get_version");
},
async setTraySettings(minimizeToTray: boolean, notifyOnMinimize: boolean) : Promise<null> {
    return await TAURI_INVOKE("set_tray_settings", { minimizeToTray, notifyOnMinimize });
},
async notify(title: string, body: string) : Promise<null> {
    return await TAURI_INVOKE("notify", { title, body });
},
async createBackup(label: string | null) : Promise<BackupMetadata> {
    return await TAURI_INVOKE("create_backup", { label });
},
async listBackups() : Promise<BackupMetadata[]> {
    return await TAURI_INVOKE("list_backups");
},
async restoreBackup(backupId: string) : Promise<null> {
    return await TAURI_INVOKE("restore_backup", { backupId });
},
async pruneBackups(maxBackups: number) : Promise<bigint> {
    return await TAURI_INVOKE("prune_backups", { maxBackups });
},
async deleteBackup(backupId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_backup", { backupId });
},
async startDownload(request: DownloadRequest) : Promise<DownloadResult> {
    return await TAURI_INVOKE("start_download", { request });
},
async cancelDownload(downloadId: string) : Promise<null> {
    return await TAURI_INVOKE("cancel_download", { downloadId });
},
async listActiveDownloads() : Promise<string[]> {
    return await TAURI_INVOKE("list_active_downloads");
},
async listJobs(statusFilter: string | null) : Promise<JobRow[]> {
    return await TAURI_INVOKE("list_jobs", { statusFilter });
},
async getJob(jobId: string) : Promise<JobRow> {
    return await TAURI_INVOKE("get_job", { jobId });
},
async cancelJob(jobId: string) : Promise<null> {
    return await TAURI_INVOKE("cancel_job", { jobId });
},
async submitDownloadJob(request: DownloadRequest) : Promise<JobRow> {
    return await TAURI_INVOKE("submit_download_job", { request });
},
async setSecret(key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("set_secret", { key, value });
},
async getSecret(key: string) : Promise<string> {
    return await TAURI_INVOKE("get_secret", { key });
},
async deleteSecret(key: string) : Promise<null> {
    return await TAURI_INVOKE("delete_secret", { key });
},
async watchPath(path: string) : Promise<null> {
    return await TAURI_INVOKE("watch_path", { path });
},
async unwatchPath(path: string) : Promise<null> {
    return await TAURI_INVOKE("unwatch_path", { path });
},
async isAppimage() : Promise<boolean> {
    return await TAURI_INVOKE("is_appimage");
},
async integrateAppimage() : Promise<null> {
    return await TAURI_INVOKE("integrate_appimage");
},
/**
 * Returns the system color-scheme preference on Linux via the Freedesktop portal.
 * Returns "dark", "light", or "no-preference".
 * On non-Linux platforms this always returns `null` (frontend should rely on matchMedia).
 */
async getSystemTheme() : Promise<string | null> {
    return await TAURI_INVOKE("get_system_theme");
},
/**
 * Sets the application window theme.
 */
async setTheme(theme: string | null) : Promise<null> {
    return await TAURI_INVOKE("set_theme", { theme });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BackupMetadata = { id: string; name: string; path: string; size_bytes: bigint; created_at: string; is_manual: boolean; label: string | null }
export type DownloadProgress = { downloadId: string; url: string; bytesDownloaded: bigint; totalBytes: bigint | null; 
/**
 * 0.0 – 100.0; `None` when content-length is unknown
 */
percent: number | null; speedBps: bigint | null; etaSecs: bigint | null; status: DownloadStatus }
export type DownloadRequest = { url: string; destDir: string; 
/**
 * If omitted, the filename is derived from the URL path.
 */
filename: string | null }
export type DownloadResult = { downloadId: string; filePath: string; totalBytes: bigint }
export type DownloadStatus = "downloading" | "complete" | "failed" | "cancelled"
export type Error = { type: "Database"; message: string } | { type: "NotFound"; message: string } | { type: "Io"; message: string } | { type: "Unknown"; message: string } | { type: "Validation"; message: string } | { type: "Network"; message: string }
export type JobKind = "download"
export type JobProgress = { jobId: string; kind: JobKind; status: JobStatus; 
/**
 * 0.0 – 100.0; `None` when progress is indeterminate
 */
percent: number | null; speedBps: bigint | null; etaSecs: bigint | null; message: string | null }
export type JobRow = { id: string; kind: JobKind; status: JobStatus; progress: number | null; message: string | null; metadata: string | null; createdAt: string; updatedAt: string }
export type JobStatus = "pending" | "running" | "completed" | "failed" | "cancelled"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}

;(() => { TAURI_CHANNEL; __makeEvents__; })();