// SPDX-License-Identifier: MIT
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getLogPath: () => __TAURI_INVOKE<string>("get_log_path"),
	exportDiagnostics: () => __TAURI_INVOKE<boolean>("export_diagnostics"),
	getDataDir: () => __TAURI_INVOKE<string | null>("get_data_dir"),
	openLogDir: () => __TAURI_INVOKE<null>("open_log_dir"),
	openDataDir: () => __TAURI_INVOKE<null>("open_data_dir"),
	resetApplication: () => __TAURI_INVOKE<null>("reset_application"),
	setLogLevel: (level: string) => __TAURI_INVOKE<null>("set_log_level", { level }),
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	setTraySettings: (minimizeToTray: boolean, notifyOnMinimize: boolean) => __TAURI_INVOKE<null>("set_tray_settings", { minimizeToTray, notifyOnMinimize }),
	notify: (title: string, body: string) => __TAURI_INVOKE<null>("notify", { title, body }),
	createBackup: (label: string | null, isManual: boolean | null) => __TAURI_INVOKE<BackupMetadata>("create_backup", { label, isManual }),
	listBackups: () => __TAURI_INVOKE<BackupMetadata[]>("list_backups"),
	restoreBackup: (backupId: string) => __TAURI_INVOKE<null>("restore_backup", { backupId }),
	pruneBackups: (maxBackups: number) => __TAURI_INVOKE<number>("prune_backups", { maxBackups }),
	deleteBackup: (backupId: string) => __TAURI_INVOKE<null>("delete_backup", { backupId }),
	listJobs: (statusFilter: string | null) => __TAURI_INVOKE<JobRow[]>("list_jobs", { statusFilter }),
	getJob: (jobId: string) => __TAURI_INVOKE<JobRow>("get_job", { jobId }),
	cancelJob: (jobId: string) => __TAURI_INVOKE<null>("cancel_job", { jobId }),
	setSecret: (key: string, value: string) => __TAURI_INVOKE<null>("set_secret", { key, value }),
	getSecret: (key: string) => __TAURI_INVOKE<string>("get_secret", { key }),
	deleteSecret: (key: string) => __TAURI_INVOKE<null>("delete_secret", { key }),
	watchPath: (path: string) => __TAURI_INVOKE<null>("watch_path", { path }),
	unwatchPath: (path: string) => __TAURI_INVOKE<null>("unwatch_path", { path }),
	getCliStatus: () => __TAURI_INVOKE<CliStatus>("get_cli_status"),
	installCli: () => __TAURI_INVOKE<null>("install_cli"),
	/**
	 *  Returns the system color-scheme preference on Linux via the Freedesktop portal.
	 *  Returns "dark", "light", or "no-preference".
	 *  On non-Linux platforms this always returns `null` (frontend should rely on matchMedia).
	 */
	getSystemTheme: () => __TAURI_INVOKE<string | null>("get_system_theme"),
	/**  Sets the application window theme. */
	setTheme: (theme: string | null) => __TAURI_INVOKE<null>("set_theme", { theme }),
	getInstallType: () => __TAURI_INVOKE<string>("get_install_type"),
};

/* Types */
export type BackupMetadata = {
	id: string,
	name: string,
	path: string,
	size_bytes: bigint,
	created_at: string,
	is_manual: boolean,
	label: string | null,
};

export type CliStatus = {
	installed: boolean,
	version: string | null,
};

export type DownloadProgress = {
	downloadId: string,
	url: string,
	bytesDownloaded: bigint,
	totalBytes: bigint | null,
	/**  0.0 – 100.0; `None` when content-length is unknown */
	percent: number | null,
	speedBps: bigint | null,
	etaSecs: bigint | null,
	status: DownloadStatus,
};

export type DownloadRequest = {
	url: string,
	destDir: string,
	/**  If omitted, the filename is derived from the URL path. */
	filename: string | null,
};

export type DownloadResult = {
	downloadId: string,
	filePath: string,
	totalBytes: bigint,
};

export type DownloadStatus = "downloading" | "complete" | "failed" | "cancelled";

export type Error = { type: "Database"; message: string } | { type: "NotFound"; message: string } | { type: "Io"; message: string } | { type: "Unknown"; message: string } | { type: "Validation"; message: string } | { type: "Network"; message: string };

export type JobKind = "download";

export type JobProgress = {
	jobId: string,
	kind: JobKind,
	status: JobStatus,
	/**  0.0 – 100.0; `None` when progress is indeterminate */
	percent: number | null,
	speedBps: bigint | null,
	etaSecs: bigint | null,
	message: string | null,
};

export type JobRow = {
	id: string,
	kind: JobKind,
	status: JobStatus,
	progress: number | null,
	message: string | null,
	metadata: string | null,
	createdAt: string,
	updatedAt: string,
};

export type JobStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

