name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - windows
          - linux
          # - macos
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-pipeline.yml
    with:
      platform: ${{ github.event.inputs.platform || 'all' }}